@base_url=http://localhost:8008
GET {{base_url}}/fizzbuzz/1
traceparent: 4133bf18-d3f1-4fd3-876c-8455d1590dc6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IllVQmhMbU52YlE9PSIsImV4cCI6MTYwMjE0MTQyNn0.XjNfYyOkr07eyo-BWhVHOiXJV50XbhfffTjFcVMgx7o
###

GET http://localhost:8888/fizzbuzz/

###

